spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
      #     新版本不支持content-type: text/html，故新写法
    servlet:
        content-type: text/html
logging:
  level:
    root: info
    com.chw: debug
  file:
    name: log/blog-dev.log
mybatis:
  configuration:
    call-setters-on-nulls: true
